### ISSUE TITLE
New architecture support

### ISSUE THREAD

**Issue by gorbypark** [Malaa-tech/expo-squircle-view#3]
Hey, thanks for the great library!  I'm just experimenting with it, but it seems it doesn't work on the new rn architecture.  Fortunately it doesn't crash or error out or anything, it just seems to my eye to display a regular view with a regular border radius.

Old arch:
<img width="392" alt="Screenshot 2024-08-22 at 10 10 15 AM" src="https://github.com/user-attachments/assets/1fe9fefb-a56b-434e-bb27-e9a66ca09228">

New arch:
<img width="392" alt="Screenshot 2024-08-22 at 10 08 44 AM" src="https://github.com/user-attachments/assets/61764b61-1279-4064-b2c7-a5b6ae66f2df">

Code is exactly the same, just toggled on the new architecture in the expo build properties plugin then rebuilt the project (expo/CNG/prebuild).

**Comment by WadhahEssam** [comment]
thanks for pointing this @gorbypark 

it should be now working in 1.1.0

https://github.com/Malaa-tech/expo-squircle-view/releases/tag/1.1.0

if you still have issues with it please let us know 🙏
